spring:
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   schema: classpath:db/schema-h2.sql
   type: com.alibaba.druid.pool.DruidDataSource
   data: classpath:db/data-h2.sql
   url: jdbc:mysql://127.0.0.1:3306/springboot
   username: root
   password: 123456